[project]
name = "Varta"
version = "0.1.0"
description = "Communication in a new way"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiokafka>=0.12.0",
    "alembic>=1.16.5",
    "asyncpg>=0.30.0",
    "boto3>=1.40.67",
    "fastapi>=0.117.1",
    "fastapi-limiter>=0.1.6",
    "msgpack>=1.1.1",
    "passlib[argon2]>=1.7.4",
    "protobuf>=6.32.1",
    "psycopg[binary]>=3.2.10",
    "pydantic[email]>=2.11.9",
    "pyjwt>=2.10.1",
    "python-multipart>=0.0.20",
    "python-socketio>=5.13.0",
    "redis>=6.4.0",
    "sqlalchemy[asyncio]>=2.0.43",
    "uvicorn[standard]>=0.37.0",
]

[dependency-groups]
dev = [
    "black>=25.9.0",
    "isort>=7.0.0",
    "ruff>=0.14.2",
]


[tool.ruff]
line-length = 88
target-version = "py311"
select = ["E", "F", "I"]
ignore = ["E501"]


[tool.isort]
profile = "black"
line_length = 88
known_first_party = ["myapp"]  # your local packages
multi_line_output = 3
include_trailing_comma = true
